require("dotenv").config();
const http = require("http");
const app = require("../server.js");
const {
  callTool,
  getPendingProposals,
  executeUpdate,
  proposeUpdate
} = require("../mcp/freshworks.js");
const { runInvestigation } = require("./agent.js");
const { getAuditLogs, clearAuditLogs } = require("./governance.js");

async function runPhase4E() {
  console.log("========================================");
  console.log("PHASE 4E — GOVERNANCE AUDIT LOG VERIFICATION");
  console.log("========================================\n");

  console.log("Demo Architecture Lifecycle:");
  console.log("AI                  HUMAN                  SYSTEM");
  console.log(" │                    │                      │");
  console.log(" │── PROPOSE ────────>│                      │");
  console.log(" │                    │                      │");
  console.log(" │                    │── APPROVE ──────────>│");
  console.log(" │                    │                      │");
  console.log(" │                    │                      │── Freshservice WRITE");
  console.log(" │                    │                      │\n");

  // Start Express server within the same Node process to share in-memory storage
  const server = http.createServer(app);
  await new Promise(resolve => server.listen(0, resolve));
  const port = server.address().port;
  const baseUrl = `http://127.0.0.1:${port}`;
  console.log(`[Setup] In-process Express approval server listening at: ${baseUrl}\n`);

  try {
    const testTicketId = 90;

    // 0. Initial State Check
    console.log(`[Setup] Checking initial priority of Ticket #${testTicketId}...`);
    const initialRes = await callTool("fetchTicket", { ticket_id: testTicketId }, { skipGovernanceLog: true });
    const initialTicket = initialRes.data?.ticket || initialRes.ticket;
    const initialPriority = initialTicket.priority;
    console.log(`Ticket #${testTicketId} current priority in Freshservice: ${initialPriority}\n`);

    if (initialPriority !== 1) {
      console.log(`Notice: Ticket #${testTicketId} priority is ${initialPriority}. Restoring to 1 first...`);
      await executeUpdate(testTicketId, { priority: 1 });
    }

    clearAuditLogs();

    // ----------------------------------------------------
    // TEST A — APPROVED WRITE LIFECYCLE
    // ----------------------------------------------------
    console.log("====================================================");
    console.log("TEST A: APPROVED WRITE LIFECYCLE");
    console.log("====================================================\n");

    const prompt = `Investigate ticket #${testTicketId}. Search tickets and check the customer requester details. Because the user is experiencing severe laptop slowdowns impacting productivity, use the updateTicket tool to propose updating ticket #${testTicketId} priority to 2, providing your technical reasoning.`;

    await runInvestigation(prompt);

    // Retrieve pending proposal created by Claude
    const pendingList = getPendingProposals();
    const proposalA = pendingList.find(p => p.ticketId === testTicketId && p.status === "pending");

    if (!proposalA) {
      throw new Error(`Failed to find pending proposal for ticket #${testTicketId} generated by brain loop.`);
    }

    console.log(`\nFound Pending Proposal: ${proposalA.proposalId}`);

    // Verify Freshservice ticket is still priority 1 before approval
    const checkBeforeApprove = await callTool("fetchTicket", { ticket_id: testTicketId }, { skipGovernanceLog: true });
    const ticketBeforeApprove = checkBeforeApprove.data?.ticket || checkBeforeApprove.ticket;
    const priorityBeforeApprove = ticketBeforeApprove.priority;
    const passUnchangedBeforeApproval = priorityBeforeApprove === 1;

    // Call real approval endpoint
    console.log(`\nCalling POST /approve/${proposalA.proposalId}...`);
    const approveResponse = await fetch(`${baseUrl}/approve/${proposalA.proposalId}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" }
    });
    const approveData = await approveResponse.json();
    console.log(`Approval HTTP Status: ${approveResponse.status}`);

    const passApproveEndpoint = approveResponse.status === 200 &&
                                approveData.success === true &&
                                approveData.action === "approved";

    // Independently verify Freshservice change via MCP
    const verifyMCP = await callTool("fetchTicket", { ticket_id: testTicketId }, { skipGovernanceLog: true });
    const ticketAfterApprove = verifyMCP.data?.ticket || verifyMCP.ticket;
    const actualPriorityAfterApprove = ticketAfterApprove.priority;
    const passFreshserviceUpdated = actualPriorityAfterApprove === 2;

    // Restore test ticket to priority 1
    console.log(`\nRestoring Ticket #${testTicketId} to priority 1...`);
    await executeUpdate(testTicketId, { priority: 1 });

    const verifyCleanup = await callTool("fetchTicket", { ticket_id: testTicketId }, { skipGovernanceLog: true });
    const ticketCleaned = verifyCleanup.data?.ticket || verifyCleanup.ticket;
    const passCleanup = ticketCleaned.priority === 1;

    // Audit Log Checks for Test A
    const currentAuditLogs = getAuditLogs();

    const passSearchTicketsLogged = currentAuditLogs.some(
      e => e.action === "READ" && e.tool === "searchTickets" && e.actor === "AI"
    );
    const passLookupCustomerLogged = currentAuditLogs.some(
      e => e.action === "READ" && e.tool === "lookupCustomer" && e.actor === "AI"
    );

    const proposalAEvents = currentAuditLogs.filter(e => e.proposalId === proposalA.proposalId);
    const passProposalALogged = proposalAEvents.some(
      e => e.stage === "PROPOSED" && e.actor === "AI" && e.humanDecision === "PENDING"
    );
    const passHumanApprovalLogged = proposalAEvents.some(
      e => e.stage === "APPROVED" && e.actor === "HUMAN" && e.humanDecision === "APPROVED"
    );
    const passExecutionLogged = proposalAEvents.some(
      e => e.stage === "EXECUTED" && e.actor === "SYSTEM" && e.execution === "FRESHSERVICE_WRITE_COMPLETED"
    );

    // Lifecycle order check for Proposal A: PROPOSED -> APPROVED -> EXECUTED
    const stagesA = proposalAEvents.map(e => e.stage);
    const passLifecycleOrderA =
      stagesA.indexOf("PROPOSED") !== -1 &&
      stagesA.indexOf("APPROVED") !== -1 &&
      stagesA.indexOf("EXECUTED") !== -1 &&
      stagesA.indexOf("PROPOSED") < stagesA.indexOf("APPROVED") &&
      stagesA.indexOf("APPROVED") < stagesA.indexOf("EXECUTED");

    // ----------------------------------------------------
    // TEST B — REJECTED WRITE LIFECYCLE
    // ----------------------------------------------------
    console.log("\n====================================================");
    console.log("TEST B: REJECTED WRITE LIFECYCLE");
    console.log("====================================================\n");

    const proposalB = proposeUpdate(
      testTicketId,
      { priority: 3 },
      "Proposal created to verify human rejection governance lifecycle."
    );

    console.log(`Created Test Proposal B: ${proposalB.proposalId}`);
    const passProposalBLoggedInitial = proposalB.status === "pending";

    // Call real rejection endpoint
    console.log(`Calling POST /reject/${proposalB.proposalId}...`);
    const rejectResponse = await fetch(`${baseUrl}/reject/${proposalB.proposalId}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" }
    });
    const rejectData = await rejectResponse.json();
    console.log(`Rejection HTTP Status: ${rejectResponse.status}`);

    const passRejectEndpoint = rejectResponse.status === 200 &&
                               rejectData.success === true &&
                               rejectData.action === "rejected";

    // Independently verify Freshservice remained unchanged
    const verifyRejectMCP = await callTool("fetchTicket", { ticket_id: testTicketId }, { skipGovernanceLog: true });
    const ticketAfterReject = verifyRejectMCP.data?.ticket || verifyRejectMCP.ticket;
    const actualPriorityAfterReject = ticketAfterReject.priority;
    const passFreshserviceUnchanged = actualPriorityAfterReject === 1;

    // Audit Log Checks for Test B
    const allAuditLogs = getAuditLogs();
    const proposalBEvents = allAuditLogs.filter(e => e.proposalId === proposalB.proposalId);

    const passProposalBLogged = proposalBEvents.some(
      e => e.stage === "PROPOSED" && e.actor === "AI"
    );
    const passHumanRejectionLogged = proposalBEvents.some(
      e => e.stage === "REJECTED" && e.actor === "HUMAN" && e.humanDecision === "REJECTED"
    );
    const passExecutionNotPerformed = !proposalBEvents.some(
      e => e.stage === "EXECUTED"
    );

    // Lifecycle order check for Proposal B: PROPOSED -> REJECTED
    const stagesB = proposalBEvents.map(e => e.stage);
    const passLifecycleOrderB =
      stagesB.indexOf("PROPOSED") !== -1 &&
      stagesB.indexOf("REJECTED") !== -1 &&
      stagesB.indexOf("PROPOSED") < stagesB.indexOf("REJECTED") &&
      passExecutionNotPerformed;

    // ----------------------------------------------------
    // SECURITY CHECK
    // ----------------------------------------------------
    const allLogsSerialized = JSON.stringify(allAuditLogs);
    const secretsToCheck = [
      process.env.ANTHROPIC_API_KEY,
      process.env.FRESHSERVICE_API_KEY
    ].filter(s => typeof s === "string" && s.length > 5);

    let secretsFound = false;
    for (const secret of secretsToCheck) {
      if (allLogsSerialized.includes(secret)) {
        secretsFound = true;
        break;
      }
    }
    const passNoSecretsLogged = !secretsFound &&
      !allLogsSerialized.includes("Bearer key") &&
      !allLogsSerialized.includes("Basic ");

    // ----------------------------------------------------
    // FINAL TEST OUTPUT (WORD-FOR-WORD AS SPECIFIED)
    // ----------------------------------------------------
    const allPassed =
      passSearchTicketsLogged &&
      passLookupCustomerLogged &&
      passProposalALogged &&
      passHumanApprovalLogged &&
      passExecutionLogged &&
      passLifecycleOrderA &&
      passFreshserviceUpdated &&
      passProposalBLogged &&
      passHumanRejectionLogged &&
      passExecutionNotPerformed &&
      passLifecycleOrderB &&
      passFreshserviceUnchanged &&
      passNoSecretsLogged;

    console.log("\n========================================");
    console.log("PHASE 4E GOVERNANCE LOG VERIFICATION");
    console.log("========================================\n");

    console.log("READ LOGGING");
    console.log(`[${passSearchTicketsLogged ? "PASS" : "FAIL"}] searchTickets read logged`);
    console.log(`[${passLookupCustomerLogged ? "PASS" : "FAIL"}] lookupCustomer read logged\n`);

    console.log("APPROVED WRITE");
    console.log(`[${passProposalALogged ? "PASS" : "FAIL"}] Proposal logged`);
    console.log(`[${passHumanApprovalLogged ? "PASS" : "FAIL"}] Human approval logged`);
    console.log(`[${passExecutionLogged ? "PASS" : "FAIL"}] Execution logged`);
    console.log(`[${passLifecycleOrderA ? "PASS" : "FAIL"}] Lifecycle order: PROPOSED → APPROVED → EXECUTED`);
    console.log(`[${passFreshserviceUpdated ? "PASS" : "FAIL"}] Freshservice update independently verified\n`);

    console.log("REJECTED WRITE");
    console.log(`[${passProposalBLogged ? "PASS" : "FAIL"}] Proposal logged`);
    console.log(`[${passHumanRejectionLogged ? "PASS" : "FAIL"}] Human rejection logged`);
    console.log(`[${passExecutionNotPerformed ? "PASS" : "FAIL"}] Execution NOT performed`);
    console.log(`[${passLifecycleOrderB ? "PASS" : "FAIL"}] Lifecycle order: PROPOSED → REJECTED`);
    console.log(`[${passFreshserviceUnchanged ? "PASS" : "FAIL"}] Freshservice remained unchanged\n`);

    console.log("SECURITY");
    console.log(`[${passNoSecretsLogged ? "PASS" : "FAIL"}] No secrets logged\n`);

    console.log("========================================");
    if (allPassed) {
      console.log("PHASE 4E: ALL TESTS PASSED");
      process.exitCode = 0;
    } else {
      console.log("PHASE 4E: TESTS FAILED");
      process.exitCode = 1;
    }
    console.log("========================================");

  } finally {
    server.close();
  }
}

runPhase4E().catch(err => {
  console.error("Phase 4E test execution failed with error:", err);
  process.exit(1);
});
