require("dotenv").config();
const http = require("http");
const app = require("../server.js");
const { callTool, getPendingProposals, executeUpdate } = require("../mcp/freshworks.js");
const { runInvestigation } = require("./agent.js");

async function runPhase4D() {
  console.log("========================================");
  console.log("PHASE 4D — END-TO-END APPROVAL VERIFICATION");
  console.log("========================================\n");

  // Start Express server within the same Node process to share in-memory proposal Map
  const server = http.createServer(app);
  await new Promise(resolve => server.listen(0, resolve));
  const port = server.address().port;
  const baseUrl = `http://127.0.0.1:${port}`;
  console.log(`[Setup] In-process Express approval server listening at: ${baseUrl}\n`);

  try {
    const testTicketId = 90;

    // 0. Initial State Check
    console.log(`[Setup] Checking initial priority of Ticket #${testTicketId}...`);
    const initialRes = await callTool("fetchTicket", { ticket_id: testTicketId });
    const initialTicket = initialRes.data?.ticket || initialRes.ticket;
    const initialPriority = initialTicket.priority;
    console.log(`Ticket #${testTicketId} current priority in Freshservice: ${initialPriority}\n`);

    if (initialPriority !== 1) {
      console.log(`Notice: Ticket #${testTicketId} priority is ${initialPriority}. Restoring to 1 first...`);
      await executeUpdate(testTicketId, { priority: 1 });
    }

    // ----------------------------------------------------
    // PART 1 — Trigger proposal through Phase 2/brain loop
    // ----------------------------------------------------
    console.log("----------------------------------------------------");
    console.log("PART 1: Triggering proposal through Phase 2/brain loop");
    console.log("----------------------------------------------------\n");

    const prompt = `Investigate ticket #${testTicketId}. Because the user is experiencing severe laptop slowdowns impacting productivity, use the updateTicket tool to propose updating ticket #${testTicketId} priority to 2, providing your technical reasoning.`;

    await runInvestigation(prompt);

    // Retrieve the pending proposal created by Claude
    const pendingList = getPendingProposals();
    const proposal = pendingList.find(p => p.ticketId === testTicketId && p.status === "pending");

    if (!proposal) {
      throw new Error(`Failed to find pending proposal for ticket #${testTicketId} generated by brain loop.`);
    }

    const hasPriority2 = proposal.updates && proposal.updates.priority === 2;
    const hasReasoning = typeof proposal.reasoning === "string" && proposal.reasoning.length > 0;
    const proposalAppearedPending = proposal.status === "pending";
    const passPart1 = proposalAppearedPending && proposal.ticketId === testTicketId && hasPriority2 && hasReasoning;

    // Check Freshservice ticket is still priority 1
    const checkBeforeApprove = await callTool("fetchTicket", { ticket_id: testTicketId });
    const ticketBeforeApprove = checkBeforeApprove.data?.ticket || checkBeforeApprove.ticket;
    const priorityBeforeApprove = ticketBeforeApprove.priority;
    const passUnchanged = priorityBeforeApprove === 1;

    // ----------------------------------------------------
    // PART 2 — Verify pending proposal output
    // ----------------------------------------------------
    console.log("\n=== PHASE 4D — PENDING PROPOSAL ===");
    console.log(`Proposal ID: ${proposal.proposalId}`);
    console.log(`Ticket: ${proposal.ticketId}`);
    console.log(`Requested Update: priority ${proposal.updates.priority}`);
    console.log(`Reasoning: ${proposal.reasoning}`);
    console.log(`Status: ${proposal.status}`);
    console.log(`Freshservice Priority: ${priorityBeforeApprove}\n`);

    // ----------------------------------------------------
    // PART 3 & 4 — Call real approval endpoint & verify response
    // ----------------------------------------------------
    console.log("----------------------------------------------------");
    console.log(`PART 3 & 4: Calling POST /approve/${proposal.proposalId}`);
    console.log("----------------------------------------------------\n");

    const approveResponse = await fetch(`${baseUrl}/approve/${proposal.proposalId}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" }
    });

    const approveData = await approveResponse.json();
    console.log(`HTTP Status: ${approveResponse.status}`);
    console.log("Response Body:", JSON.stringify(approveData, null, 2));

    const passPart4 = approveResponse.status === 200 &&
                      approveData.success === true &&
                      approveData.action === "approved" &&
                      approveData.proposal?.status === "approved";

    // ----------------------------------------------------
    // PART 5 — Independently verify Freshservice change via MCP
    // ----------------------------------------------------
    console.log("\n----------------------------------------------------");
    console.log("PART 5: Independently verifying Freshservice via MCP");
    console.log("----------------------------------------------------\n");

    const verifyMCP = await callTool("fetchTicket", { ticket_id: testTicketId });
    const ticketAfterApprove = verifyMCP.data?.ticket || verifyMCP.ticket;
    const actualPriority = ticketAfterApprove.priority;

    console.log("=== PHASE 4D — FRESHSERVICE VERIFICATION ===");
    console.log(`Ticket: ${testTicketId}`);
    console.log("Expected Priority: 2");
    console.log(`Actual Priority: ${actualPriority}`);

    const passPart5 = actualPriority === 2;
    if (passPart5) {
      console.log("REAL FRESHSERVICE UPDATE: CONFIRMED\n");
    } else {
      console.log("REAL FRESHSERVICE UPDATE: FAILED\n");
    }

    // ----------------------------------------------------
    // PART 6 — Restore the test ticket to priority 1
    // ----------------------------------------------------
    console.log("----------------------------------------------------");
    console.log("PART 6: Restoring Ticket #90 to priority 1");
    console.log("----------------------------------------------------\n");

    await executeUpdate(testTicketId, { priority: 1 });

    const verifyCleanup = await callTool("fetchTicket", { ticket_id: testTicketId });
    const ticketCleaned = verifyCleanup.data?.ticket || verifyCleanup.ticket;
    const cleanedPriority = ticketCleaned.priority;

    console.log("=== PHASE 4D — CLEANUP ===");
    console.log(`Ticket: ${testTicketId}`);
    console.log(`Priority after cleanup: ${cleanedPriority}`);

    const passCleanup = cleanedPriority === 1;
    if (passCleanup) {
      console.log("Cleanup: CONFIRMED\n");
    } else {
      console.log("Cleanup: FAILED\n");
    }

    // ----------------------------------------------------
    // PART 7 — Final checklist and report
    // ----------------------------------------------------
    console.log("----------------------------------------------------");
    console.log("VERIFICATION CHECKLIST");
    console.log("----------------------------------------------------");
    console.log(`[${passPart1 ? "PASS" : "FAIL"}] Phase 2 loop created a proposal`);
    console.log(`[${proposalAppearedPending ? "PASS" : "FAIL"}] Proposal appeared as pending`);
    console.log(`[${passUnchanged ? "PASS" : "FAIL"}] Freshservice remained unchanged before approval`);
    console.log(`[${approveResponse.status === 200 ? "PASS" : "FAIL"}] Real POST /approve/:actionId endpoint was called`);
    console.log(`[${approveResponse.status === 200 ? "PASS" : "FAIL"}] Approval endpoint returned HTTP 200`);
    console.log(`[${approveData.proposal?.status === "approved" ? "PASS" : "FAIL"}] Proposal became approved`);
    console.log(`[${passPart5 ? "PASS" : "FAIL"}] Freshservice actually changed to priority 2`);
    console.log(`[${passPart5 ? "PASS" : "FAIL"}] Independent MCP fetch confirmed priority 2`);
    console.log(`[${passCleanup ? "PASS" : "FAIL"}] Ticket restored to priority 1`);
    console.log(`[${passCleanup ? "PASS" : "FAIL"}] Independent MCP fetch confirmed priority 1\n`);

    const allPassed = passPart1 && proposalAppearedPending && passUnchanged && passPart4 && passPart5 && passCleanup;

    console.log("========================================");
    console.log("PHASE 4D VERIFICATION");
    console.log("========================================");
    console.log(`Brain → Proposal         ${passPart1 ? "PASS" : "FAIL"}`);
    console.log(`Pending State            ${proposalAppearedPending ? "PASS" : "FAIL"}`);
    console.log(`Approval Endpoint        ${passPart4 ? "PASS" : "FAIL"}`);
    console.log(`Freshservice Write       ${passPart5 ? "PASS" : "FAIL"}`);
    console.log(`Independent Verification ${passPart5 ? "PASS" : "FAIL"}`);
    console.log(`Cleanup                  ${passCleanup ? "PASS" : "FAIL"}\n`);

    if (allPassed) {
      console.log("PHASE 4D: ALL TESTS PASSED");
      console.log("========================================");
      process.exitCode = 0;
    } else {
      console.log("PHASE 4D: TESTS FAILED");
      console.log("========================================");
      process.exitCode = 1;
    }
  } finally {
    server.close();
  }
}

runPhase4D().catch(err => {
  console.error("Phase 4D failed with error:", err);
  process.exit(1);
});
